
stages:
  - test

test_job:
  stage: test
  tags:
    - shell
  only:
    - Lesson3
  script:
    - mvn clean test -DsuiteXmlFile=testng.xml
  artifacts:
    when: always
    paths:
      - allure-results
