
stages:
  - test

test_job:
  stage: test
  tags:
    - gb-runner
  only:
    - Lesson8 ci cd
  script:
    - mvn clean test -DsuiteXmlFile=testng.xml
  artifacts:
    when: always
    paths:
      - allure-results
